---
ID: "37bfc7d0-ed84-4a9a-af81-2779803e43e3"
Parent: "89c7729c-b267-4d67-be43-fbb6838998b0"
Template: "89c7729c-b267-4d67-be43-fbb6838998b0"
Path: /sitecore/templates/Project/Example/Home/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20171002T110351Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
