---
ID: "2bae9560-210f-49aa-a054-55f8333d0fad"
Parent: "48aabb11-29d3-452d-9f63-aea7d78c5e82"
Template: "48aabb11-29d3-452d-9f63-aea7d78c5e82"
Path: /sitecore/templates/Foundation/MultiTenant/Folder Templates/Site/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20171002T064510Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
